theme: jekyll-theme-dinky

<script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>

<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="dark" data-type="VERTICAL" data-vanity="tushal-kakadiya-8b35b9139" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://de.linkedin.com/in/tushal-kakadiya-8b35b9139?trk=profile-badge">Tushal Kakadiya</a></div>
