remote_theme: pages-themes/modernist@v0.2.0
plugins: 
- jekyll-remote-theme

linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light"
       data-type="VERTICAL" data-vanity="{PROFILENAME}" data-version="v1">
    <a class="badge-base__link LI-simple-link" href="https://www.linkedin.com/in/tushal-kakadiya?trk=profile-badge">
      Tushal Kakadiya
    </a>
  </div>
